version: '3.8'

services:
  postgres:
    image: postgres:11.5-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_DB=portfolio
      - POSTGRES_PASSWORD=root
    ports:
      - '5432:5432'
    restart: unless-stopped
